package com.emsays.path.gui;

import com.emsays.path.Database;
import com.emsays.path.Util;
import com.emsays.path.dao.app.CompanyDAO;
import com.emsays.path.dto.app.CompanyDTO;
import com.emsays.path.dto.app.YearDTO;
import javax.swing.JOptionPane;

public class pnlAddYear extends javax.swing.JPanel
{

	frmWrapper vParent;
	CompanyDTO vObjCompany;

	/**
	 * Creates new form pnlLogin
	 */
	public pnlAddYear(frmWrapper vParent, CompanyDTO vObjCompany)
	{
		initComponents();
		this.vParent = vParent;
		this.vObjCompany = vObjCompany;
	}

	private boolean checkIsValid()
	{
		if (txtDateFrom.getText() == null || txtDateFrom.getText().equals(""))
		{
			JOptionPane.showMessageDialog(null, "Financial year date from is required", "Message", JOptionPane.INFORMATION_MESSAGE);
			return false;
		}
		else if (!Util.isDateValid(txtDateFrom.getText()))
		{
			JOptionPane.showMessageDialog(null, "Date from is invalid", "Message", JOptionPane.INFORMATION_MESSAGE);
			return false;
		}
		else if (txtDateTo.getText() == null || txtDateTo.getText().equals(""))
		{
			JOptionPane.showMessageDialog(null, "Financial year date to is required", "Message", JOptionPane.INFORMATION_MESSAGE);
			return false;
		}
		else if (!Util.isDateValid(txtDateTo.getText()))
		{
			JOptionPane.showMessageDialog(null, "Date to is invalid", "Message", JOptionPane.INFORMATION_MESSAGE);
			return false;
		}

		return true;
	}

	private void handleClickBtnSave()
	{
		if (checkIsValid())
		{
			YearDTO vObjYear = new YearDTO(
				Util.mConvertStringToDate(txtDateFrom.getText()),
				Util.mConvertStringToDate(txtDateTo.getText())
			);
			vObjCompany.addYear(vObjYear);
			if (new CompanyDAO().mSave(vObjCompany))
			{
				Database.createDB(Integer.toString(vObjYear.getId()));
				JOptionPane.showMessageDialog(null, "Year created successfully", "Message", JOptionPane.INFORMATION_MESSAGE);
				vParent.addPanel(new pnlGateway(vParent));
			}
		}
	}

	private void handleClickBtnCancel()
	{
		vParent.addPanel(new pnlGateway(vParent));
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents()
        {

                btnSave = new javax.swing.JButton();
                btnCancel = new javax.swing.JButton();
                txtDateFrom = new javax.swing.JTextField();
                jLabel2 = new javax.swing.JLabel();
                txtDateTo = new javax.swing.JTextField();
                jLabel3 = new javax.swing.JLabel();

                btnSave.setText("Save");
                btnSave.setPreferredSize(new java.awt.Dimension(75, 32));
                btnSave.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                btnSaveActionPerformed(evt);
                        }
                });

                btnCancel.setText("Cancel");
                btnCancel.setPreferredSize(new java.awt.Dimension(75, 32));
                btnCancel.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                btnCancelActionPerformed(evt);
                        }
                });

                jLabel2.setText("From Date");

                jLabel3.setText("To Date");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(6, 6, 6)
                                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(6, 6, 6)
                                                                .addComponent(jLabel2))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel3)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(txtDateFrom, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                                        .addComponent(txtDateTo))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(txtDateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtDateTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
        }// </editor-fold>//GEN-END:initComponents

        private void btnSaveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSaveActionPerformed
        {//GEN-HEADEREND:event_btnSaveActionPerformed
		// TODO add your handling code here:
		handleClickBtnSave();
        }//GEN-LAST:event_btnSaveActionPerformed

        private void btnCancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCancelActionPerformed
        {//GEN-HEADEREND:event_btnCancelActionPerformed
		// TODO add your handling code here:
		handleClickBtnCancel();
        }//GEN-LAST:event_btnCancelActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnCancel;
        private javax.swing.JButton btnSave;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JTextField txtDateFrom;
        private javax.swing.JTextField txtDateTo;
        // End of variables declaration//GEN-END:variables
}
