package com.emsays.path.gui;

import com.emsays.path.CommonUIActions;
import static com.emsays.path.CommonUIActions.showMessageBox;
import com.emsays.path.Database;
import com.emsays.path.dao.SMSTemplateSer;
import com.emsays.path.dto.SMSTemplateDTO;
import javax.swing.JPanel;

public class pnlAddSMSTemplate extends javax.swing.JPanel
{

	MyFormWrapper frmWrapper;
	MyPanelBack pnlBack;
	boolean vModeAdd;
	SMSTemplateDTO smsTemplate;

	SMSTemplateSer smsTemplateSer;

	public pnlAddSMSTemplate(MyFormWrapper vParent, MyPanelBack pnlBack)
	{
		initComponents();
		myInit();

		this.frmWrapper = vParent;
		this.pnlBack = pnlBack;
		this.vModeAdd = true;
		this.smsTemplate = new SMSTemplateDTO();

	}

	public pnlAddSMSTemplate(MyFormWrapper vParent, MyPanelBack pnlBack, SMSTemplateDTO vObjSMSTemplate)
	{
		initComponents();
		myInit();

		this.frmWrapper = vParent;
		this.pnlBack = pnlBack;
		this.vModeAdd = false;
		this.smsTemplate = vObjSMSTemplate;

		txtName.setText(vObjSMSTemplate.getName());
		taMessage.setText(vObjSMSTemplate.getMessage());
	}

	private void myInit()
	{
		smsTemplateSer = new SMSTemplateSer(Database.getSessionCompanyYear());
	}

	private boolean checkIsValid(StringBuilder errorMsg)
	{
		if (txtName.getText() == null || txtName.getText().equals(""))
		{
			errorMsg.append("Name is required");
			return false;
		}
		if (taMessage.getText() == null || taMessage.getText().equals(""))
		{
			errorMsg.append("Message is required");
			return false;
		}

		return true;
	}

	private void clearBoxes()
	{
		txtName.setText(null);
		taMessage.setText(null);

		smsTemplate = new SMSTemplateDTO();

		txtName.requestFocus();
	}

	private void handleClickBtnSave()
	{
		StringBuilder errorMsg = new StringBuilder();
		if (!checkIsValid(errorMsg))
		{
			showMessageBox(errorMsg.toString());
			return;
		}

		smsTemplate.setName(txtName.getText());
		smsTemplate.setMessage(taMessage.getText());

		boolean result;

		if (vModeAdd)
		{
			result = (smsTemplateSer.create(smsTemplate, errorMsg));
		}
		else
		{
			result = (smsTemplateSer.update(smsTemplate, errorMsg));
		}

		if (result)
		{
			CommonUIActions.showMessageBox("SMSTemplate saved successfully");
		}
		else
		{
			CommonUIActions.showMessageBox(errorMsg.toString());
			return;
		}

		if (vModeAdd)
		{
			clearBoxes();
		}
		else
		{
			this.showListForm();
		}

	}

	private void handleClickBtnCancel()
	{
		this.showListForm();
	}

	private void showListForm()
	{
		pnlBack.refreshData();
		frmWrapper.addPanel((JPanel) pnlBack);
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents()
        {

                txtName = new javax.swing.JTextField();
                btnSave = new javax.swing.JButton();
                btnCancel = new javax.swing.JButton();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                taMessage = new javax.swing.JTextArea();

                txtName.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                txtNameActionPerformed(evt);
                        }
                });

                btnSave.setText("Save");
                btnSave.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                btnSaveActionPerformed(evt);
                        }
                });

                btnCancel.setText("Cancel");
                btnCancel.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                btnCancelActionPerformed(evt);
                        }
                });

                jLabel1.setText("Template Name");

                jLabel2.setText("Message");

                taMessage.setColumns(20);
                taMessage.setRows(5);
                jScrollPane1.setViewportView(taMessage);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnSave)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnCancel))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel1)
                                                        .addComponent(jLabel2))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(txtName)
                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnSave)
                                        .addComponent(btnCancel))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
        }// </editor-fold>//GEN-END:initComponents

        private void btnSaveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSaveActionPerformed
        {//GEN-HEADEREND:event_btnSaveActionPerformed
		handleClickBtnSave();
        }//GEN-LAST:event_btnSaveActionPerformed

        private void btnCancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCancelActionPerformed
        {//GEN-HEADEREND:event_btnCancelActionPerformed
		handleClickBtnCancel();
        }//GEN-LAST:event_btnCancelActionPerformed

        private void txtNameActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtNameActionPerformed
        {//GEN-HEADEREND:event_txtNameActionPerformed
		// TODO add your handling code here:
        }//GEN-LAST:event_txtNameActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnCancel;
        private javax.swing.JButton btnSave;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTextArea taMessage;
        private javax.swing.JTextField txtName;
        // End of variables declaration//GEN-END:variables
}
