package com.emsays.path.gui;

import com.emsays.path.CommonUIActions;
import com.emsays.path.Database;
import com.emsays.path.ObjectForCombobox;
import com.emsays.path.Util;
import com.emsays.path.dao.CustomerSer;
import com.emsays.path.dao.PackageSer;
import com.emsays.path.dto.CustomerDTO;
import com.emsays.path.dto.PackageDTO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;

public class pnlAddChildOnly extends javax.swing.JPanel
{

	MyFormWrapper frmWrapper;
	MyPanelBack pnlBack;
	boolean vModeAdd;
	CustomerDTO childOld;
	CustomerDTO parentCustomer;
	CustomerDTO childCustomer;

	List<PackageDTO> packages;

	public pnlAddChildOnly(MyFormWrapper vParent, MyPanelBack pnlBack, CustomerDTO parentCustomer)
	{
		initComponents();

		this.parentCustomer = parentCustomer;
		this.frmWrapper = vParent;
		this.pnlBack = pnlBack;
		this.vModeAdd = true;

		mFillDropDowns();

		this.childCustomer = new CustomerDTO();
		this.parentCustomer.addChild(childCustomer);
	}

	public pnlAddChildOnly(MyFormWrapper vParent, MyPanelBack pnlBack, CustomerDTO parentCustomer, CustomerDTO childCustomer)
	{
		initComponents();
		this.frmWrapper = vParent;
		this.pnlBack = pnlBack;
		this.vModeAdd = false;

		mFillDropDowns();

		this.childOld = new CustomerDTO(childCustomer);
		this.parentCustomer = parentCustomer;
		this.childCustomer = childCustomer;

		txtAccountNo.setText(String.valueOf(childCustomer.getAccountNo()));
		txtCustomerName.setText(childCustomer.getCustomerName());
		txtMobile.setText(childCustomer.getMobile());
		cmbPackage.setSelectedItem(childCustomer.getPackage().getName());
		txtNote.setText(childCustomer.getNote());

	}

	private void mFillDropDowns()
	{
		packages = new PackageSer(Database.getSessionCompanyYear()).retrieve();

		CommonUIActions.fillComboBox(cmbPackage, new ArrayList<ObjectForCombobox>(packages));
	}

	private boolean checkIsValid(StringBuilder errorMsg)
	{

		if (!Util.isNumeric(txtAccountNo.getText()))
		{
			errorMsg.append("Account no is invalid");
			return false;
		}

		return true;
	}

	private void clearBoxes()
	{
		txtAccountNo.setText(null);
		txtCustomerName.setText(null);
		txtMobile.setText(null);
		cmbPackage.setSelectedIndex(0);
		txtNote.setText(null);

		txtAccountNo.requestFocus();
	}

	private void handleClickBtnSave()
	{
		StringBuilder errorMsg = new StringBuilder();

		if (!checkIsValid(errorMsg))
		{
			return;
		}

		childCustomer.setAccountNo(Integer.valueOf(txtAccountNo.getText()));
		childCustomer.setCustomerName(txtCustomerName.getText());
		childCustomer.setMobile(txtMobile.getText());
		childCustomer.setPackage(packages.get(cmbPackage.getSelectedIndex() - 1));
		childCustomer.setNote(txtNote.getText());

		boolean res;
		if (vModeAdd)
		{
			res = new CustomerSer(Database.getSessionCompanyYear()).createChild(parentCustomer, childCustomer, errorMsg);
		}
		else
		{
			res = new CustomerSer(Database.getSessionCompanyYear()).updateChild(parentCustomer, childOld, childCustomer, errorMsg);
		}

		if (res)
		{
			CommonUIActions.showMessageBox("Data saved successfully");
		}
		else
		{
			CommonUIActions.showMessageBox(errorMsg.equals("") ? "Error saving data" : errorMsg.toString());
			return;
		}

		if (vModeAdd)
		{
			clearBoxes();
		}
		else
		{
			this.showListForm();
		}

	}

	private void handleClickBtnCancel()
	{
		this.showListForm();
	}

	private void showListForm()
	{
		pnlBack.refreshData();
		frmWrapper.addPanel((JPanel) pnlBack);
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents()
        {

                txtAccountNo = new javax.swing.JTextField();
                txtCustomerName = new javax.swing.JTextField();
                txtMobile = new javax.swing.JTextField();
                cmbPackage = new javax.swing.JComboBox<>();
                txtNote = new javax.swing.JTextField();
                btnSave = new javax.swing.JButton();
                btnCancel = new javax.swing.JButton();
                jLabel9 = new javax.swing.JLabel();
                jLabel24 = new javax.swing.JLabel();
                jLabel18 = new javax.swing.JLabel();
                jLabel26 = new javax.swing.JLabel();
                jLabel20 = new javax.swing.JLabel();

                btnSave.setText("Save");
                btnSave.setPreferredSize(new java.awt.Dimension(75, 32));
                btnSave.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                btnSaveActionPerformed(evt);
                        }
                });

                btnCancel.setText("Cancel");
                btnCancel.setPreferredSize(new java.awt.Dimension(75, 32));
                btnCancel.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                btnCancelActionPerformed(evt);
                        }
                });

                jLabel9.setText("Customer Name");

                jLabel24.setText("Mobile");

                jLabel18.setText("Note");

                jLabel26.setText("Account No");

                jLabel20.setText("Package");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel24)
                                                        .addComponent(jLabel20)
                                                        .addComponent(jLabel26)
                                                        .addComponent(jLabel9)
                                                        .addComponent(jLabel18))
                                                .addGap(9, 9, 9)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(txtCustomerName, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtAccountNo, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(cmbPackage, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(txtMobile, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtNote, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(4, 4, 4)
                                                .addComponent(jLabel26))
                                        .addComponent(txtAccountNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel9)
                                        .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel24))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cmbPackage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel20))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtNote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
        }// </editor-fold>//GEN-END:initComponents

        private void btnSaveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSaveActionPerformed
        {//GEN-HEADEREND:event_btnSaveActionPerformed
		// TODO add your handling code here:
		handleClickBtnSave();
        }//GEN-LAST:event_btnSaveActionPerformed

        private void btnCancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCancelActionPerformed
        {//GEN-HEADEREND:event_btnCancelActionPerformed
		// TODO add your handling code here:
		handleClickBtnCancel();
        }//GEN-LAST:event_btnCancelActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnCancel;
        private javax.swing.JButton btnSave;
        private javax.swing.JComboBox<String> cmbPackage;
        private javax.swing.JLabel jLabel18;
        private javax.swing.JLabel jLabel20;
        private javax.swing.JLabel jLabel24;
        private javax.swing.JLabel jLabel26;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JTextField txtAccountNo;
        private javax.swing.JTextField txtCustomerName;
        private javax.swing.JTextField txtMobile;
        private javax.swing.JTextField txtNote;
        // End of variables declaration//GEN-END:variables
}
