package com.emsays.path.gui;

import com.emsays.path.CommonUIActions;
import com.emsays.path.Database;
import com.emsays.path.Util;
import com.emsays.path.dao.InvoiceSer;
import com.emsays.path.dto.CustomerDTO;
import com.emsays.path.dto.InvoiceDTO;
import java.util.Calendar;
import javax.swing.JPanel;

public class pnlAddInvoice extends javax.swing.JPanel
{

	MyFormWrapper frmWrapper;
	MyPanelBack pnlBack;
	boolean vModeAdd;
	CustomerDTO customer;
	InvoiceDTO invoice;

	public pnlAddInvoice(MyFormWrapper vParent, MyPanelBack pnlBack, CustomerDTO customer)
	{
		initComponents();

		myInit();

		this.frmWrapper = vParent;
		this.pnlBack = pnlBack;
		this.vModeAdd = true;
		this.customer = customer;
		this.invoice = new InvoiceDTO();

		txtAmount.setText(String.valueOf(customer.getAmount()));
	}

	public pnlAddInvoice(MyFormWrapper vParent, MyPanelBack pnlBack, CustomerDTO customer, InvoiceDTO invoice)
	{
		initComponents();

		myInit();

		this.frmWrapper = vParent;
		this.pnlBack = pnlBack;
		this.vModeAdd = false;
		this.customer = customer;
		this.invoice = invoice;

		cmbYear.setSelectedItem(String.valueOf(invoice.getYear()));
		cmbMonth.setSelectedItem(String.valueOf(invoice.getMonth()));
		txtAmount.setText(String.valueOf(invoice.getAmount()));
		txtNote.setText(invoice.getNote());

	}

	private void myInit()
	{
		Calendar cal = Calendar.getInstance();

		cmbYear.addItem(String.valueOf(cal.get(Calendar.YEAR) - 1));
		cmbYear.addItem(String.valueOf(cal.get(Calendar.YEAR)));
		cmbYear.addItem(String.valueOf(cal.get(Calendar.YEAR) + 1));

		for (int i = 1; i <= 12; i++)
		{
			cmbMonth.addItem(String.valueOf(i));
		}
	}

	private boolean checkIsValid(StringBuilder errorMsg)
	{
		if (txtAmount.getText() == null || txtAmount.getText().equals(""))
		{
			errorMsg.append("Amount is required");
			return false;
		}

		if (!Util.isNumeric(txtAmount.getText()))
		{
			errorMsg.append("Amount is invalid");
			return false;
		}

		return true;
	}

	private void handleClickBtnSave()
	{
		StringBuilder errorMsg = new StringBuilder();
		if (!checkIsValid(errorMsg))
		{
			CommonUIActions.showMessageBox(errorMsg.toString());
			return;
		}

		invoice.setYear(Integer.parseInt(cmbYear.getSelectedItem().toString()));
		invoice.setMonth(Integer.parseInt(cmbMonth.getSelectedItem().toString()));
		invoice.setAmount(Integer.parseInt(txtAmount.getText()));
		invoice.setNote(txtNote.getText());

		boolean res;
		if (vModeAdd)
		{
			res = (new InvoiceSer(Database.getSessionCompanyYear()).create(customer, invoice, errorMsg));
		}
		else
		{
			res = (new InvoiceSer(Database.getSessionCompanyYear()).update(customer, invoice, errorMsg));
		}

		if (res)
		{
			CommonUIActions.showMessageBox("Data saved successfully");
		}
		else
		{
			CommonUIActions.showMessageBox(errorMsg.equals("") ? "Error saving data" : errorMsg.toString());
			return;
		}

		if (vModeAdd)
		{
			this.showListForm();
		}
		else
		{
			this.showListForm();
		}

	}

	private void handleClickBtnCancel()
	{
		this.showListForm();
	}

	private void showListForm()
	{
		pnlBack.refreshData();
		frmWrapper.addPanel((JPanel) pnlBack);
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents()
        {

                cmbYear = new javax.swing.JComboBox<>();
                cmbMonth = new javax.swing.JComboBox<>();
                txtAmount = new javax.swing.JTextField();
                txtNote = new javax.swing.JTextField();
                btnSave = new javax.swing.JButton();
                btnCancel = new javax.swing.JButton();
                jLabel12 = new javax.swing.JLabel();
                jLabel10 = new javax.swing.JLabel();
                jLabel11 = new javax.swing.JLabel();
                jLabel13 = new javax.swing.JLabel();

                btnSave.setText("Save");
                btnSave.setPreferredSize(new java.awt.Dimension(75, 32));
                btnSave.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                btnSaveActionPerformed(evt);
                        }
                });

                btnCancel.setText("Cancel");
                btnCancel.setPreferredSize(new java.awt.Dimension(75, 32));
                btnCancel.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                btnCancelActionPerformed(evt);
                        }
                });

                jLabel12.setText("Amount");

                jLabel10.setText("Year");

                jLabel11.setText("Month");

                jLabel13.setText("Note");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel10)
                                                        .addComponent(jLabel11)
                                                        .addComponent(jLabel13)
                                                        .addComponent(jLabel12))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtNote, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(cmbYear, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(cmbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cmbYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10))
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel11)
                                        .addComponent(cmbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtNote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
        }// </editor-fold>//GEN-END:initComponents

        private void btnSaveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSaveActionPerformed
        {//GEN-HEADEREND:event_btnSaveActionPerformed
		// TODO add your handling code here:
		handleClickBtnSave();
        }//GEN-LAST:event_btnSaveActionPerformed

        private void btnCancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCancelActionPerformed
        {//GEN-HEADEREND:event_btnCancelActionPerformed
		// TODO add your handling code here:
		handleClickBtnCancel();
        }//GEN-LAST:event_btnCancelActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnCancel;
        private javax.swing.JButton btnSave;
        private javax.swing.JComboBox<String> cmbMonth;
        private javax.swing.JComboBox<String> cmbYear;
        private javax.swing.JLabel jLabel10;
        private javax.swing.JLabel jLabel11;
        private javax.swing.JLabel jLabel12;
        private javax.swing.JLabel jLabel13;
        private javax.swing.JTextField txtAmount;
        private javax.swing.JTextField txtNote;
        // End of variables declaration//GEN-END:variables
}
