package com.emsays.path.gui;

import com.emsays.path.APIHelper;
import com.emsays.path.Database;
import com.emsays.path.GV;
import com.emsays.path.Util;
import com.emsays.path.dto.api.RegisterResDTO;
import com.emsays.path.dao.app.AppInfoSer;
import javax.swing.JOptionPane;

public class pnlActivation extends javax.swing.JPanel
{

	frmWrapper vParent;

	/**
	 * Creates new form pnlLogin
	 */
	public pnlActivation(frmWrapper vParent)
	{
		initComponents();
		this.vParent = vParent;

		if (GV.getAppStatus() == GV.enmAppStatus.REGISTERED)
		{
			AppInfoSer vObjAppInfoSer = new AppInfoSer(Database.getSessionApp());

			txtAgentKey.setText(
					vObjAppInfoSer.get(AppInfoSer.AppInfoKey.AgentKey)
			);

			txtClientKey.setText(
					vObjAppInfoSer.get(AppInfoSer.AppInfoKey.ClientKey)
			);

			txtName.setText(
					vObjAppInfoSer.get(AppInfoSer.AppInfoKey.Name)
			);

			txtAgentKey.setEnabled(false);
			txtClientKey.setEnabled(false);
			txtName.setEnabled(false);
			btnRegister.setEnabled(false);
		}
	}

	private boolean checkIsValid()
	{
		if (txtAgentKey.getText() == null || txtAgentKey.getText().equals(""))
		{
			JOptionPane.showMessageDialog(null, "Key1 is required", "Message", JOptionPane.INFORMATION_MESSAGE);
			return false;
		}
		else if (!this.mIsValidUUID(txtAgentKey.getText()))
		{
			JOptionPane.showMessageDialog(null, "Key1 is invalid", "Message", JOptionPane.INFORMATION_MESSAGE);
			return false;
		}
		else if (txtClientKey.getText() == null || txtClientKey.getText().equals(""))
		{
			JOptionPane.showMessageDialog(null, "Key2 is required", "Message", JOptionPane.INFORMATION_MESSAGE);
			return false;
		}
		else if (!this.mIsValidUUID(txtClientKey.getText()))
		{
			JOptionPane.showMessageDialog(null, "Key2 is invalid", "Message", JOptionPane.INFORMATION_MESSAGE);
			return false;
		}
		else if (txtName.getText() == null || txtName.getText().equals(""))
		{
			JOptionPane.showMessageDialog(null, "Name is required", "Message", JOptionPane.INFORMATION_MESSAGE);
			return false;
		}
		else if (!this.mIsValidName(txtName.getText()))
		{
			JOptionPane.showMessageDialog(null, "Name can contain only alpha, numeric, space and dash only", "Message", JOptionPane.INFORMATION_MESSAGE);
			return false;
		}

		return true;
	}

	private void mBtnRegisterClickHandler()
	{
		if (checkIsValid())
		{

			if (Util.mIsNetConnected())
			{

				AppInfoSer vObjAppInfoSer = new AppInfoSer(Database.getSessionApp());
				String instanceKey = vObjAppInfoSer.get(AppInfoSer.AppInfoKey.InstanceKey);

				RegisterResDTO vObjRegResModel = new APIHelper(
						txtAgentKey.getText(),
						txtClientKey.getText(),
						instanceKey,
						GV.APP_TYPE_ID,
						txtName.getText(),
						"",
						""
				).register();

				System.out.println(vObjRegResModel.isDone());
				System.out.println(vObjRegResModel.getCode());
				System.out.println(vObjRegResModel.getMsg());

				if (vObjRegResModel.isDone())
				{
					JOptionPane.showMessageDialog(null, "Registered successfully", "Message", JOptionPane.INFORMATION_MESSAGE);

					vObjAppInfoSer.set(AppInfoSer.AppInfoKey.StatusId, "2");
					vObjAppInfoSer.set(AppInfoSer.AppInfoKey.AgentKey, txtAgentKey.getText());
					vObjAppInfoSer.set(AppInfoSer.AppInfoKey.ClientKey, txtClientKey.getText());
					vObjAppInfoSer.set(AppInfoSer.AppInfoKey.Name, txtName.getText());

					GV.setAppStatus(GV.enmAppStatus.REGISTERED);

					handleClickBtnCancel();
				}
				else
				{
					JOptionPane.showMessageDialog(null, vObjRegResModel.getMsg(), "Message", JOptionPane.INFORMATION_MESSAGE);
				}
			}
			else
			{
				JOptionPane.showMessageDialog(null, "Internet connection not available", "Message", JOptionPane.INFORMATION_MESSAGE);
			}

		}
	}

	private void handleClickBtnCancel()
	{
		vParent.addPanel(new pnlGateway(vParent));
	}

	private boolean mIsValidUUID(String vString)
	{
		return (vString.matches("[a-z0-9]{32}"));
	}

	private boolean mIsValidName(String vString)
	{
		return (vString.matches("[a-zA-Z0-9\\s\\-]+"));
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents()
        {

                btnRegister = new javax.swing.JButton();
                btnCancel = new javax.swing.JButton();
                txtAgentKey = new javax.swing.JTextField();
                txtClientKey = new javax.swing.JTextField();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                btnUnregister = new javax.swing.JButton();
                txtName = new javax.swing.JTextField();
                jLabel3 = new javax.swing.JLabel();

                btnRegister.setText("Register");
                btnRegister.setPreferredSize(new java.awt.Dimension(75, 32));
                btnRegister.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                btnRegisterActionPerformed(evt);
                        }
                });

                btnCancel.setText("Cancel");
                btnCancel.setPreferredSize(new java.awt.Dimension(75, 32));
                btnCancel.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                btnCancelActionPerformed(evt);
                        }
                });

                jLabel1.setText("Key 1");

                jLabel2.setText("Key 2");

                btnUnregister.setText("Unregister");
                btnUnregister.setPreferredSize(new java.awt.Dimension(75, 32));
                btnUnregister.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                btnUnregisterActionPerformed(evt);
                        }
                });

                jLabel3.setText("Name");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel1)
                                                        .addComponent(jLabel3))
                                                .addGap(21, 21, 21)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(txtAgentKey, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                                        .addComponent(txtClientKey)
                                                        .addComponent(txtName)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(btnUnregister, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                                                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(4, 4, 4)
                                                .addComponent(jLabel1))
                                        .addComponent(txtAgentKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(txtClientKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnUnregister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
        }// </editor-fold>//GEN-END:initComponents

        private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnRegisterActionPerformed
        {//GEN-HEADEREND:event_btnRegisterActionPerformed
			// TODO add your handling code here:
			this.mBtnRegisterClickHandler();
        }//GEN-LAST:event_btnRegisterActionPerformed

        private void btnUnregisterActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnUnregisterActionPerformed
        {//GEN-HEADEREND:event_btnUnregisterActionPerformed
			// TODO add your handling code here:
        }//GEN-LAST:event_btnUnregisterActionPerformed

        private void btnCancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCancelActionPerformed
        {//GEN-HEADEREND:event_btnCancelActionPerformed
			// TODO add your handling code here:
			this.handleClickBtnCancel();
        }//GEN-LAST:event_btnCancelActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnCancel;
        private javax.swing.JButton btnRegister;
        private javax.swing.JButton btnUnregister;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JTextField txtAgentKey;
        private javax.swing.JTextField txtClientKey;
        private javax.swing.JTextField txtName;
        // End of variables declaration//GEN-END:variables
}
