package com.emsays.path.gui;

import java.awt.BorderLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.TreeSelectionModel;

public class pnlMenu2 extends javax.swing.JPanel implements MyFormWrapper
{

	public enum enmMenus
	{
		COMPANY_INFO("Company Info"),
		SMS_TEMPLATE("SMS Template"),
		MOBILE("Mobile"),
		AREA("Area"),
		COLLECT_FROM("Collect From"),
		PAYMENT_TYPE("Payment Type"),
		PACKAGE("Package"),
		OFFER("Offer"),
		DASHBOARD("Dashboard"),
		CUSTOMER("Customer"),
		INVOICE("Invoice"),
		RECEIPT("Receipt"),
		DUE("Due");

		private final String text;

		/**
		 * @param text
		 */
		private enmMenus(final String text)
		{
			this.text = text;
		}

		/* (non-Javadoc)
		 * @see java.lang.Enum#toString()
		 */
		@Override
		public String toString()
		{
			return text;
		}
	}

	frmWrapper vParent;

	public pnlMenu2(frmWrapper vParent)
	{
		initComponents();
		jTree1.getSelectionModel().setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);

		this.vParent = vParent;

	}

	private void mTreeSelectionChangeHandler()
	{
		//Returns the last path element of the selection.
		//This method is useful only when the selection model allows a single selection.
		DefaultMutableTreeNode node = (DefaultMutableTreeNode) jTree1.getLastSelectedPathComponent();

		if (node == null)
		{
			return;
		}

		Object nodeInfo = node.getUserObject();

		if (node.isLeaf())
		{
			String menulItem = (String) nodeInfo;

			jPanel1.removeAll();

			if (menulItem.equals(enmMenus.AREA.toString()))
			{
				addPanel(new pnlListArea(this));
			}
			else if (menulItem.equals(enmMenus.COLLECT_FROM.toString()))
			{
				addPanel(new pnlListCollectFrom(this));
			}
			else if (menulItem.equals(enmMenus.CUSTOMER.toString()))
			{
				addPanel(new pnlListCustomer(this));
			}
			else if (menulItem.equals(enmMenus.INVOICE.toString()))
			{
				addPanel(new pnlListInvoice(this));
			}
			else if (menulItem.equals(enmMenus.OFFER.toString()))
			{
				addPanel(new pnlListOffer(this));
			}
			else if (menulItem.equals(enmMenus.PACKAGE.toString()))
			{
				addPanel(new pnlListPackage(this));
			}
			else if (menulItem.equals(enmMenus.PAYMENT_TYPE.toString()))
			{
				addPanel(new pnlListPaymentType(this));
			}
			else if (menulItem.equals(enmMenus.RECEIPT.toString()))
			{
				addPanel(new pnlListReceipt(this));
			}
			else if (menulItem.equals(enmMenus.MOBILE.toString()))
			{
				addPanel(new pnlMobile(this));
			}
			else if (menulItem.equals(enmMenus.DASHBOARD.toString()))
			{
				addPanel(new pnlDashboard(this));
			}
			else if (menulItem.equals(enmMenus.SMS_TEMPLATE.toString()))
			{
				addPanel(new pnlListSMSTemplate(this));
			}
			else if (menulItem.equals(enmMenus.COMPANY_INFO.toString()))
			{
				addPanel(new pnlCompanyInfo(this));
			}

			jPanel1.repaint();
			jPanel1.revalidate();
		}
	}

	@Override
	public void addPanel(JPanel vJPanel)
	{
		jPanel1.removeAll();

		if (vJPanel.getClass() == pnlMenu2.class
			|| vJPanel.getClass() == pnlListCollectFrom.class
			|| vJPanel.getClass() == pnlListOffer.class
			|| vJPanel.getClass() == pnlListPackage.class
			|| vJPanel.getClass() == pnlListPaymentType.class
			|| vJPanel.getClass() == pnlListCustomer.class
			|| vJPanel.getClass() == pnlListInvoice.class
			|| vJPanel.getClass() == pnlListReceipt.class
			|| vJPanel.getClass() == pnlAddReceipt.class
			|| vJPanel.getClass() == pnlMobile.class)
		{
			jPanel1.setLayout(new BorderLayout());
			jPanel1.add(vJPanel);
		}
		else
		{
			jPanel1.setLayout(new GridBagLayout());
			jPanel1.add(vJPanel, new GridBagConstraints());
			//jPanel1.setLayout(new GridLayout(0, 1));
			//jPanel1.add(vJPanel);
		}

		jPanel1.repaint();
		jPanel1.revalidate();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents()
        {

                jScrollPane2 = new javax.swing.JScrollPane();
                jTree1 = new javax.swing.JTree();
                jScrollPane3 = new javax.swing.JScrollPane();
                jPanel1 = new javax.swing.JPanel();

                javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Menu");
                javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Dashboard");
                treeNode1.add(treeNode2);
                treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Customer");
                treeNode1.add(treeNode2);
                treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Invoice");
                treeNode1.add(treeNode2);
                treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Receipt");
                treeNode1.add(treeNode2);
                treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Reports");
                javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Due");
                treeNode2.add(treeNode3);
                treeNode1.add(treeNode2);
                treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Admin");
                treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Mobile");
                treeNode2.add(treeNode3);
                treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Area");
                treeNode2.add(treeNode3);
                treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Offer");
                treeNode2.add(treeNode3);
                treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Package");
                treeNode2.add(treeNode3);
                treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Payment Type");
                treeNode2.add(treeNode3);
                treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Collect From");
                treeNode2.add(treeNode3);
                treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("SMS Template");
                treeNode2.add(treeNode3);
                treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Company Info");
                treeNode2.add(treeNode3);
                treeNode1.add(treeNode2);
                jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
                jTree1.setExpandsSelectedPaths(false);
                jTree1.setShowsRootHandles(false);
                jTree1.setToggleClickCount(1);
                jTree1.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener()
                {
                        public void valueChanged(javax.swing.event.TreeSelectionEvent evt)
                        {
                                jTree1ValueChanged(evt);
                        }
                });
                jScrollPane2.setViewportView(jTree1);

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 488, Short.MAX_VALUE)
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 411, Short.MAX_VALUE)
                );

                jScrollPane3.setViewportView(jPanel1);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                );
        }// </editor-fold>//GEN-END:initComponents

        private void jTree1ValueChanged(javax.swing.event.TreeSelectionEvent evt)//GEN-FIRST:event_jTree1ValueChanged
        {//GEN-HEADEREND:event_jTree1ValueChanged
		// TODO add your handling code here:
		mTreeSelectionChangeHandler();
        }//GEN-LAST:event_jTree1ValueChanged


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JPanel jPanel1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JScrollPane jScrollPane3;
        private javax.swing.JTree jTree1;
        // End of variables declaration//GEN-END:variables
}
