package com.emsays.path.gui;

import com.emsays.path.GV;
import com.emsays.path.LogWriter;
import com.emsays.path.Server;

public class pnlMobile extends javax.swing.JPanel implements LogWriter
{

	MyFormWrapper vParent;
	Server server;

	public pnlMobile(MyFormWrapper vParent)
	{
		initComponents();

		this.vParent = vParent;
	}

	private void handleBtnStartClick()
	{
		server = GV.getServer();
		server.setLogWriter(this);
		server.startServer();
		lblAddress.setText(server.getIpAddress() + ":" + server.getPort());
	}

	private void handleClickBtnStop()
	{
		server.stopServer();
	}

	private void handleBtnSendClick()
	{
		server.send();
	}

	private void handlebtnReceiveClick()
	{
		server.receive();
	}

	@Override
	public void writeLog(String s)
	{
		taLog.setText(taLog.getText() + s + "\n");
		taLog.setCaretPosition(taLog.getText().length());
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        fileChooser = new javax.swing.JFileChooser();
        btnStart = new javax.swing.JButton();
        btnSend = new javax.swing.JButton();
        lblAddress = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taLog = new javax.swing.JTextArea();
        btnReceive = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();

        fileChooser.setAcceptAllFileFilterUsed(false);

        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnStartActionPerformed(evt);
            }
        });

        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSendActionPerformed(evt);
            }
        });

        lblAddress.setText("Name");

        taLog.setColumns(20);
        taLog.setRows(5);
        jScrollPane2.setViewportView(taLog);

        btnReceive.setText("Receive");
        btnReceive.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnReceiveActionPerformed(evt);
            }
        });

        btnStop.setText("Stop");
        btnStop.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnStopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAddress)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnStop, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnReceive, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 424, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAddress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStop)
                    .addComponent(btnStart)
                    .addComponent(btnSend)
                    .addComponent(btnReceive))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

        private void btnStartActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnStartActionPerformed
        {//GEN-HEADEREND:event_btnStartActionPerformed
			// TODO add your handling code here:
			handleBtnStartClick();
        }//GEN-LAST:event_btnStartActionPerformed

        private void btnSendActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSendActionPerformed
        {//GEN-HEADEREND:event_btnSendActionPerformed
			// TODO add your handling code here:
			handleBtnSendClick();
        }//GEN-LAST:event_btnSendActionPerformed

        private void btnReceiveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnReceiveActionPerformed
        {//GEN-HEADEREND:event_btnReceiveActionPerformed
			// TODO add your handling code here:
			handlebtnReceiveClick();
        }//GEN-LAST:event_btnReceiveActionPerformed

        private void btnStopActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnStopActionPerformed
        {//GEN-HEADEREND:event_btnStopActionPerformed
			// TODO add your handling code here:
			handleClickBtnStop();
        }//GEN-LAST:event_btnStopActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReceive;
    private javax.swing.JButton btnSend;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStop;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JTextArea taLog;
    // End of variables declaration//GEN-END:variables
}
