package com.emsays.path.gui;

public class pnlMenu extends javax.swing.JPanel implements MyPanelBack
{

	MyFormWrapper vParent;

	/**
	 * Creates new form pnlLogin
	 */
	public pnlMenu(MyFormWrapper vParent)
	{
		initComponents();
		this.vParent = vParent;
	}

	private void mBtnAddCollectFromClickHandler()
	{
		vParent.addPanel(new pnlAddCollectFrom(vParent, this));
	}

	private void mBtnListCollectFromClickHandler()
	{
		vParent.addPanel(new pnlListCollectFrom(vParent));
	}

	private void mBtnAddPaymentTypeClickHandler()
	{
		vParent.addPanel(new pnlAddPaymentType(vParent, this));
	}

	private void mBtnListPaymentTypeClickHandler()
	{
		vParent.addPanel(new pnlListPaymentType(vParent));
	}

	private void mBtnAddPackageClickHandler()
	{
		vParent.addPanel(new pnlAddPackage(vParent, this));
	}

	private void mBtnListPackageClickHandler()
	{
		vParent.addPanel(new pnlListPackage(vParent));
	}

	private void mBtnAddOfferClickHandler()
	{
		vParent.addPanel(new pnlAddOffer(vParent, this));
	}

	private void mBtnListOfferClickHandler()
	{
		vParent.addPanel(new pnlListOffer(vParent));
	}

	private void mBtnAddCustomerClickHandler()
	{
		vParent.addPanel(new pnlAddCustomerChild(vParent));
	}

	private void mBtnListCustomerClickHandler()
	{
		vParent.addPanel(new pnlListCustomer(vParent));
	}

	private void mBtnAddInvoiceClickHandler()
	{
		//vParent.addPanel(new pnlAddCustomer(vParent, this));
	}

	private void mBtnListInvoiceClickHandler()
	{
		vParent.addPanel(new pnlListInvoice(vParent));
	}

	private void mBtnAddReceiptClickHandler()
	{
		//vParent.addPanel(new pnlAddReceipt(vParent, this));
	}

	private void mBtnListReceiptClickHandler()
	{
		vParent.addPanel(new pnlListReceipt(vParent));
	}

	private void mBtnLedgerClickHandler()
	{
	}

	private void mBtnDueClickHandler()
	{
	}

	@Override
	public void refreshData()
	{

	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents()
        {

                jPanel1 = new javax.swing.JPanel();
                btnAddCustomer = new javax.swing.JButton();
                btnListCustomer = new javax.swing.JButton();
                jPanel4 = new javax.swing.JPanel();
                btnAddOffer = new javax.swing.JButton();
                btnListOffer = new javax.swing.JButton();
                jPanel5 = new javax.swing.JPanel();
                btnAddPackage = new javax.swing.JButton();
                btnListPackage = new javax.swing.JButton();
                jPanel6 = new javax.swing.JPanel();
                btnLedger = new javax.swing.JButton();
                btnDue = new javax.swing.JButton();
                jPanel3 = new javax.swing.JPanel();
                btnAddReceipt = new javax.swing.JButton();
                btnListReceipt = new javax.swing.JButton();
                jPanel7 = new javax.swing.JPanel();
                btnAddPaymentType = new javax.swing.JButton();
                btnListPaymentType = new javax.swing.JButton();
                jPanel8 = new javax.swing.JPanel();
                btnAddCollectFrom = new javax.swing.JButton();
                btnListCollectFrom = new javax.swing.JButton();
                jPanel2 = new javax.swing.JPanel();
                btnAddInvoice = new javax.swing.JButton();
                btnListInvoice = new javax.swing.JButton();

                setMinimumSize(new java.awt.Dimension(0, 0));

                jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Customer"));

                btnAddCustomer.setText("Add");
                btnAddCustomer.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                btnAddCustomerActionPerformed(evt);
                        }
                });

                btnListCustomer.setText("List");
                btnListCustomer.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                btnListCustomerActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnAddCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                        .addComponent(btnListCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAddCustomer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnListCustomer))
                );

                jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Offer"));

                btnAddOffer.setText("Add");
                btnAddOffer.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                btnAddOfferActionPerformed(evt);
                        }
                });

                btnListOffer.setText("List");
                btnListOffer.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                btnListOfferActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
                jPanel4.setLayout(jPanel4Layout);
                jPanel4Layout.setHorizontalGroup(
                        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnAddOffer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnListOffer, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                );
                jPanel4Layout.setVerticalGroup(
                        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btnAddOffer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnListOffer))
                );

                jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Package"));

                btnAddPackage.setText("Add");
                btnAddPackage.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                btnAddPackageActionPerformed(evt);
                        }
                });

                btnListPackage.setText("List");
                btnListPackage.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                btnListPackageActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
                jPanel5.setLayout(jPanel5Layout);
                jPanel5Layout.setHorizontalGroup(
                        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnAddPackage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnListPackage, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                );
                jPanel5Layout.setVerticalGroup(
                        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(btnAddPackage)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnListPackage))
                );

                jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Reports"));

                btnLedger.setText("Ledger");
                btnLedger.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                btnLedgerActionPerformed(evt);
                        }
                });

                btnDue.setText("Due");
                btnDue.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                btnDueActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
                jPanel6.setLayout(jPanel6Layout);
                jPanel6Layout.setHorizontalGroup(
                        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnDue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLedger, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                jPanel6Layout.setVerticalGroup(
                        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(btnLedger)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDue))
                );

                jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Receipt"));

                btnAddReceipt.setText("Add");
                btnAddReceipt.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                btnAddReceiptActionPerformed(evt);
                        }
                });

                btnListReceipt.setText("List");
                btnListReceipt.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                btnListReceiptActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnAddReceipt, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                        .addComponent(btnListReceipt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                jPanel3Layout.setVerticalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnAddReceipt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnListReceipt))
                );

                jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Payment Type"));

                btnAddPaymentType.setText("Add");
                btnAddPaymentType.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                btnAddPaymentTypeActionPerformed(evt);
                        }
                });

                btnListPaymentType.setText("List");
                btnListPaymentType.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                btnListPaymentTypeActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
                jPanel7.setLayout(jPanel7Layout);
                jPanel7Layout.setHorizontalGroup(
                        jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnAddPaymentType, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                        .addComponent(btnListPaymentType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                jPanel7Layout.setVerticalGroup(
                        jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(btnAddPaymentType)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnListPaymentType))
                );

                jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Collect From"));

                btnAddCollectFrom.setText("Add");
                btnAddCollectFrom.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                btnAddCollectFromActionPerformed(evt);
                        }
                });

                btnListCollectFrom.setText("List");
                btnListCollectFrom.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                btnListCollectFromActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
                jPanel8.setLayout(jPanel8Layout);
                jPanel8Layout.setHorizontalGroup(
                        jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnAddCollectFrom, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                        .addComponent(btnListCollectFrom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                jPanel8Layout.setVerticalGroup(
                        jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(btnAddCollectFrom)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnListCollectFrom))
                );

                jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Invoice"));

                btnAddInvoice.setText("Add");
                btnAddInvoice.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                btnAddInvoiceActionPerformed(evt);
                        }
                });

                btnListInvoice.setText("List");
                btnListInvoice.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                btnListInvoiceActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnAddInvoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnListInvoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnAddInvoice)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnListInvoice))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                );
        }// </editor-fold>//GEN-END:initComponents

        private void btnAddPackageActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAddPackageActionPerformed
        {//GEN-HEADEREND:event_btnAddPackageActionPerformed
		// TODO add your handling code here:
		mBtnAddPackageClickHandler();
        }//GEN-LAST:event_btnAddPackageActionPerformed

        private void btnListPackageActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnListPackageActionPerformed
        {//GEN-HEADEREND:event_btnListPackageActionPerformed
		// TODO add your handling code here:
		mBtnListPackageClickHandler();
        }//GEN-LAST:event_btnListPackageActionPerformed

        private void btnAddCustomerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAddCustomerActionPerformed
        {//GEN-HEADEREND:event_btnAddCustomerActionPerformed
		// TODO add your handling code here:
		mBtnAddCustomerClickHandler();
        }//GEN-LAST:event_btnAddCustomerActionPerformed

        private void btnAddOfferActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAddOfferActionPerformed
        {//GEN-HEADEREND:event_btnAddOfferActionPerformed
		// TODO add your handling code here:
		mBtnAddOfferClickHandler();
        }//GEN-LAST:event_btnAddOfferActionPerformed

        private void btnListOfferActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnListOfferActionPerformed
        {//GEN-HEADEREND:event_btnListOfferActionPerformed
		// TODO add your handling code here:
		mBtnListOfferClickHandler();
        }//GEN-LAST:event_btnListOfferActionPerformed

        private void btnListCustomerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnListCustomerActionPerformed
        {//GEN-HEADEREND:event_btnListCustomerActionPerformed
		// TODO add your handling code here:
		mBtnListCustomerClickHandler();
        }//GEN-LAST:event_btnListCustomerActionPerformed

        private void btnAddReceiptActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAddReceiptActionPerformed
        {//GEN-HEADEREND:event_btnAddReceiptActionPerformed
		// TODO add your handling code here:
		mBtnAddReceiptClickHandler();
        }//GEN-LAST:event_btnAddReceiptActionPerformed

        private void btnAddPaymentTypeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAddPaymentTypeActionPerformed
        {//GEN-HEADEREND:event_btnAddPaymentTypeActionPerformed
		// TODO add your handling code here:
		mBtnAddPaymentTypeClickHandler();
        }//GEN-LAST:event_btnAddPaymentTypeActionPerformed

        private void btnListPaymentTypeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnListPaymentTypeActionPerformed
        {//GEN-HEADEREND:event_btnListPaymentTypeActionPerformed
		// TODO add your handling code here:
		mBtnListPaymentTypeClickHandler();
        }//GEN-LAST:event_btnListPaymentTypeActionPerformed

        private void btnAddCollectFromActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAddCollectFromActionPerformed
        {//GEN-HEADEREND:event_btnAddCollectFromActionPerformed
		// TODO add your handling code here:
		mBtnAddCollectFromClickHandler();
        }//GEN-LAST:event_btnAddCollectFromActionPerformed

        private void btnListCollectFromActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnListCollectFromActionPerformed
        {//GEN-HEADEREND:event_btnListCollectFromActionPerformed
		// TODO add your handling code here:
		mBtnListCollectFromClickHandler();
        }//GEN-LAST:event_btnListCollectFromActionPerformed

        private void btnAddInvoiceActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAddInvoiceActionPerformed
        {//GEN-HEADEREND:event_btnAddInvoiceActionPerformed
		// TODO add your handling code here:
        }//GEN-LAST:event_btnAddInvoiceActionPerformed

        private void btnListInvoiceActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnListInvoiceActionPerformed
        {//GEN-HEADEREND:event_btnListInvoiceActionPerformed
		// TODO add your handling code here:
		mBtnListInvoiceClickHandler();
        }//GEN-LAST:event_btnListInvoiceActionPerformed

        private void btnListReceiptActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnListReceiptActionPerformed
        {//GEN-HEADEREND:event_btnListReceiptActionPerformed
		// TODO add your handling code here:
		mBtnListReceiptClickHandler();
        }//GEN-LAST:event_btnListReceiptActionPerformed

        private void btnLedgerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnLedgerActionPerformed
        {//GEN-HEADEREND:event_btnLedgerActionPerformed
		// TODO add your handling code here:
		mBtnLedgerClickHandler();
        }//GEN-LAST:event_btnLedgerActionPerformed

        private void btnDueActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnDueActionPerformed
        {//GEN-HEADEREND:event_btnDueActionPerformed
		// TODO add your handling code here:
		mBtnDueClickHandler();
        }//GEN-LAST:event_btnDueActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnAddCollectFrom;
        private javax.swing.JButton btnAddCustomer;
        private javax.swing.JButton btnAddInvoice;
        private javax.swing.JButton btnAddOffer;
        private javax.swing.JButton btnAddPackage;
        private javax.swing.JButton btnAddPaymentType;
        private javax.swing.JButton btnAddReceipt;
        private javax.swing.JButton btnDue;
        private javax.swing.JButton btnLedger;
        private javax.swing.JButton btnListCollectFrom;
        private javax.swing.JButton btnListCustomer;
        private javax.swing.JButton btnListInvoice;
        private javax.swing.JButton btnListOffer;
        private javax.swing.JButton btnListPackage;
        private javax.swing.JButton btnListPaymentType;
        private javax.swing.JButton btnListReceipt;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JPanel jPanel4;
        private javax.swing.JPanel jPanel5;
        private javax.swing.JPanel jPanel6;
        private javax.swing.JPanel jPanel7;
        private javax.swing.JPanel jPanel8;
        // End of variables declaration//GEN-END:variables
}
