package com.emsays.path.gui;

import com.emsays.path.Database;
import com.emsays.path.dao.SMSTemplateSer;
import com.emsays.path.dto.SMSTemplateDTO;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.List;
import javax.swing.DefaultListModel;

public class SMSTemplateDialog extends javax.swing.JDialog
{

	boolean res = false;

	List<SMSTemplateDTO> smsTemplateDTOs;
	SMSTemplateSer smsTemplateSer;

	public SMSTemplateDialog(java.awt.Frame parent, boolean modal)
	{
		super(parent, modal);
		initComponents();

		Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
		setLocation(dim.width / 2 - getSize().width / 2, dim.height / 2 - getSize().height / 2);

		smsTemplateSer = new SMSTemplateSer(Database.getSessionCompanyYear());
		smsTemplateDTOs = smsTemplateSer.retrieve();

		DefaultListModel<String> lstModel = new DefaultListModel<String>();
		for (SMSTemplateDTO smsTemplateDTO : smsTemplateDTOs)
		{
			lstModel.addElement(smsTemplateDTO.getName());
		}
		lstTemplates.setModel(lstModel);
	}

	private void handleTemplateChange()
	{
		taMessage.setText(smsTemplateDTOs.get(lstTemplates.getSelectedIndex()).getMessage());
	}

	public boolean run()
	{
		this.setVisible(true);
		return res;
	}

	public String getMessage()
	{
		return taMessage.getText();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents()
        {

                jLabel1 = new javax.swing.JLabel();
                jLabel8 = new javax.swing.JLabel();
                btnBrowser = new javax.swing.JButton();
                btnSend = new javax.swing.JButton();
                jScrollPane2 = new javax.swing.JScrollPane();
                lstTemplates = new javax.swing.JList<>();
                jScrollPane3 = new javax.swing.JScrollPane();
                taMessage = new javax.swing.JTextArea();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

                jLabel1.setText("Template");

                jLabel8.setText("Message");

                btnBrowser.setText("Cancel");
                btnBrowser.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                btnBrowserActionPerformed(evt);
                        }
                });

                btnSend.setText("Send");
                btnSend.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                btnSendActionPerformed(evt);
                        }
                });

                lstTemplates.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
                lstTemplates.addVetoableChangeListener(new java.beans.VetoableChangeListener()
                {
                        public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException
                        {
                                lstTemplatesVetoableChange(evt);
                        }
                });
                lstTemplates.addListSelectionListener(new javax.swing.event.ListSelectionListener()
                {
                        public void valueChanged(javax.swing.event.ListSelectionEvent evt)
                        {
                                lstTemplatesValueChanged(evt);
                        }
                });
                jScrollPane2.setViewportView(lstTemplates);

                taMessage.setColumns(20);
                taMessage.setRows(5);
                jScrollPane3.setViewportView(taMessage);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnSend)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnBrowser))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(6, 6, 6)
                                                                .addComponent(jLabel1)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel8)
                                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                                        .addComponent(jScrollPane3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnBrowser)
                                        .addComponent(btnSend))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void btnBrowserActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnBrowserActionPerformed
        {//GEN-HEADEREND:event_btnBrowserActionPerformed
		res = false;
		dispose();
        }//GEN-LAST:event_btnBrowserActionPerformed

        private void btnSendActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSendActionPerformed
        {//GEN-HEADEREND:event_btnSendActionPerformed
		this.res = true;
		dispose();
        }//GEN-LAST:event_btnSendActionPerformed

        private void lstTemplatesVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException//GEN-FIRST:event_lstTemplatesVetoableChange
        {//GEN-HEADEREND:event_lstTemplatesVetoableChange

        }//GEN-LAST:event_lstTemplatesVetoableChange

        private void lstTemplatesValueChanged(javax.swing.event.ListSelectionEvent evt)//GEN-FIRST:event_lstTemplatesValueChanged
        {//GEN-HEADEREND:event_lstTemplatesValueChanged
		if (!evt.getValueIsAdjusting())//This line prevents double events
		{
			handleTemplateChange();
		}
        }//GEN-LAST:event_lstTemplatesValueChanged

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnBrowser;
        private javax.swing.JButton btnSend;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JScrollPane jScrollPane3;
        private javax.swing.JList<String> lstTemplates;
        private javax.swing.JTextArea taMessage;
        // End of variables declaration//GEN-END:variables
}
