package com.emsays.path.gui;

import com.emsays.path.GV;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JProgressBar;

public class SplashScreen extends javax.swing.JFrame
{

	/**
	 * Creates new form SplashScreen
	 */
	public SplashScreen()
	{
		initComponents();
	}

	public JProgressBar getProgressBar()
	{
		return progressBar;
	}

	public JLabel getLblStatus()
	{
		return lblStatus;
	}

	public ImageIcon getBackgroundImageIcon()
	{
		return new javax.swing.ImageIcon(GV.IMAGE_DIR + "/splash.jpg");
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents()
        {

                lblStatus = new javax.swing.JLabel();
                progressBar = new javax.swing.JProgressBar();
                lblImage = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setMaximumSize(new java.awt.Dimension(500, 250));
                setMinimumSize(new java.awt.Dimension(500, 250));
                setUndecorated(true);
                setPreferredSize(new java.awt.Dimension(500, 250));
                getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                lblStatus.setForeground(new java.awt.Color(255, 255, 255));
                lblStatus.setText("jLabel2");
                getContentPane().add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 222, -1, -1));

                progressBar.setIndeterminate(true);
                getContentPane().add(progressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 500, -1));

                lblImage.setIcon(getBackgroundImageIcon());
                getContentPane().add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel lblImage;
        private javax.swing.JLabel lblStatus;
        private javax.swing.JProgressBar progressBar;
        // End of variables declaration//GEN-END:variables
}
